### ISSUE TITLE
Config warning

### ISSUE THREAD

**Issue by sinclairtarget** [sinclairtarget/um#2]
On older Ruby versions, using um prints warnings about using a deprecated `Config` class. Renaming the `Config` module would be an easy solution.

**Comment by sinclairtarget** [comment]
```
/usr/local/Cellar/um/1.1/lib/um/config.rb:1:in `<top (required)>': Use RbConfig instead of obsolete and deprecated Config.
/usr/local/Cellar/um/1.1/lib/um/config.rb:1:in `<top (required)>': Use RbConfig instead of obsolete and deprecated Config.
```
